### PR TITLE
Day2review

### PR DESCRIPTION
**Pull request by robinagandhi**
@MLHale I got all the way to the end of Unit one. For Unit 2 I ran into issues with ember, npm and bower install on my fresh ubuntu vm. So rather than debug installation issues, I tried to download the dev VM from your dropbox, but it kept failing giving an error message "file too large". I did not want to tie up your first principles update to Day 2, so I created a pull request for stuff this far. 

I suggest you review the changes carefully before merging. 

**Update1** Sat 10:50 PM : Instead of downloading a zip of all VM files, I was able to start download of the individual files after copying them to my dropbox folder. I may be able to finish this review tomorrow much quickly. I spent way too much time debugging install issues today on my fresh ubuntu vm.

### CODE REVIEW

**Comment by MLHale** [comment]
I just looked over changes and nothing appears to be breaking. I'm accepting all. The expository portions are certainly improved and it appears you just added commands that I missed rather than any changes related to the fresh VM environment differences. Don't worry about merge conflicts on the cybersecurity first principles. I'll have them self-contained and I can just drop them in the final version.

**Comment by robinagandhi** [comment]
The vmdk download got upto 1.6GB and then failed.... 👎 
I will try again in the morning.

**Comment by MLHale** [comment]
I can zip it and send you a link to the zip - so that if the download fails you only miss out on a 100mb chunk. Might take a bit to upload to dropbox though.

---

Matt Hale, Ph.D.
Assistant Professor of Information Assurance
University of Nebraska Omaha
Office: PKI 174D, (402) 554-3978tel:%28402%29%20554-3978

**Comment by robinagandhi** [comment]
Yeah! Finally got it downloaded this morning. 💯 I will continue with the review now. I pulled down your latest changes too.

**Comment by robinagandhi** [comment]
At what point is the Dev VM on dropbox snapshotted? most of the steps in unit 2 seem to be already done. 

Also the repos in this dev vm are initialized with "gencybertest" account. So my push fails.

**Comment by robinagandhi** [comment]
rm -rf ed everything and started again from step1. It was hard to trace what edits were made and what were not.

**Comment by robinagandhi** [comment]
Step 4: urls.py looks different than your image. 

This is already in there.
```
from api import views
```
and the urlpatterns are very different in your image. Here is my version:

screen shot 2016-07-17 at 9 40 25 am

**Comment by MLHale** [comment]
Robin,


I may have accidentally uploaded my working copy instead of the starter file - sorry.


----------------------------------------------------
Matt Hale, Ph.D.
Assistant Professor of Information Assurance
University of Nebraska Omaha
Office: PKI 174D, (402) 554-3978<tel:%28402%29%20554-3978>
________________________________

**Pull request merged**
